micronaut:
  application:
    name: bookcat
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}"'
    enabled: false
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/bookcat
    driverClassName: org.postgresql.Driver
    username: postgres
    password: password
    dialect: POSTGRES
jpa.default.properties.hibernate.hbm2ddl.auto: update
liquibase:
  datasources:
    default:
      change-log: 'classpath:db/liquibase-changelog.xml'
